### ISSUE TITLE
Rssi Filter

### ISSUE THREAD

**Issue by engineearemotetechnologiessl** [weliem/blessed-bluez#4]
It seems that the library does not detect beacons with rssi lower than -80. Is there any way to change this configuration?

**Comment by weliem** [comment]
I did this because I got a lot of connection errors when connecting to peripherals with a very low rssi. But for scanning beacons that is indeed less relevant.

I will look into making this value configurable.

**Comment by engineearemotetechnologiessl** [comment]
Hello,
I see that this issue has a pull request, but it hasn't had any change in a while, do you have any plan to resolve it?

**Comment by weliem** [comment]
The person submitting the PR doesn't seem to be responding to my comments. I think I will fix this myself then.

**Comment by dobestler** [comment]
Is there any progress on this issue?

**Comment by weliem** [comment]
Fixed in the latest release (0.40)

**Comment by dobestler** [comment]
Thanks.

I see a problem when setting rssi values smaller than a certain value around -130:
central.setRssiThreshold((short) -120); -- THIS WORKS
central.setRssiThreshold((short) -130); -- THIS DOES NOT WORK

17:48:15.017 [Central-queue] ERROR BluetoothCentralManager - command exception for central
17:48:15.018 [Central-queue] ERROR BluetoothCentralManager - Invalid arguments in method call 

And no scan results are coming in either. 

I have tried to set the min Value for the RSSI Filter. I think it would be better to give the option to setting the scan filters so that one could e.g. remove the RSSI Filter altogether.

**Comment by weliem** [comment]
Hmmm, sounds like Bluez is imposing some limits...have to dig into the Bluez source code I guess...

**Comment by weliem** [comment]
Ok, looked at the Bluez source code and the minimum you can set is -127.

Fixed in release 0.51
